(function(g){var window=this;'use strict';var G3=function(a){a.publish("cardstatechange",a.Wk()&&a.Cp()?1:0)},H3=function(a,b){var c=g.cb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Upb=function(a){var b=g.Ss(a);
a=g.Vs(a);return new g.Gs(b.x,b.y,a.width,a.height)},Vpb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.xB(a,b,function(){g.yB(e);c.apply(a,arguments)},d)},K3=function(a){a=g.fb(a);
delete I3[a];g.gd(I3)&&J3&&J3.stop()},Xpb=function(){J3||(J3=new g.Lv(function(){Wpb()},20));
var a=J3;a.isActive()||a.start()},Wpb=function(){var a=g.lb();
g.Uc(I3,function(b){Ypb(b,a)});
g.gd(I3)||Xpb()},L3=function(a,b,c,d){g.Yv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Ypb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Zpb(a,a.progress);a.progress==1?(a.j=0,K3(a),a.onFinish(),a.Zr()):a.isPlaying()&&a.SM()},Zpb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},$pb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},M3=function(a,b,c,d,e){L3.call(this,b,c,d,e);
this.element=a},aqb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
M3.call(this,a,b,c,d,e)},bqb=function(a){return Math.pow(a,3)},cqb=function(a){return 3*a*a-2*a*a*a},dqb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},N3=function(a){return a.baseUrl||null},O3=function(a,b){return g.Pt(g.as(a,b),function(c){return!!c})},eqb=function(a,b,c){function d(pa){var ia=pa.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var ta=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var T=f(ia.subscriberCountWithUnsubscribeText);var Ha=f(ia.subscriberCountText)}else T=f(ia.subscriberCountText),Ha=f(ia.subscriberCountWithSubscribeText);var x=null;if(pa.signinEndpoint){x=H3(pa,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,Ma;x=(Ma=g.V((ba=ia.signInEndpoint)==null?void 0:ba.commandMetadata,g.z2))==null?void 0:
Ma.url}if(!x)return null}return ta&&(aa||x)?{subscribed:ia.subscribed,subscribeText:ta,subscribeCount:T,unsubscribeText:aa,unsubscribeCount:Ha,enabled:ia.enabled,signinUrl:x,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ia=[],ta=pa.videoId;ta&&ia.push("v="+ta);(ta=pa.playlistId)&&ia.push("list="+ta);(pa=pa.startTimeSeconds)&&ia.push("t="+pa);return"/watch?"+ia.join("&")}}
function f(pa){if(!pa)return null;var ia=pa.simpleText;return ia?ia:pa.runs?g.as(pa.runs,function(ta){return ta.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,w=!1,A=null,C=null,F=null,H=null,L=null,N=null;if(h==="VIDEO")g.V(l,g.mF)?m=g.V(l,g.mF).url:(N=g.V(l,g.LS),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.V(l,g.mF)?m=g.V(l,g.mF).url:(N=g.V(l,g.LS),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(w=H3(l,"browseEndpoint","browseId"))u=w,m="/channel/"+u;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=H3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=H3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=H3(b,"title","accessibility","accessibilityData","label");var P=b.endpoint?b.endpoint.clickTrackingParams:
null,fa="";if(b.metadata){var ma=f(b.metadata);ma&&(fa=ma)}return{id:"element-"+c,type:h,title:f(b.title),metadata:fa,callToAction:f(b.callToAction),BX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,rF:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,b$:n,sessionData:P?{itct:P}:null,qea:q,ND:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:O3(b.impressionUrls||[],N3),Q9:O3(b.hovercardShowUrls||[],N3),clickUrls:O3(l.loggingUrls||[],N3),visualElement:g.qE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},fqb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O3(a.impressionUrls||[],N3),elements:O3(a.elements||[],function(d,e){return eqb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.qE(a.trackingParams));return c},gqb=function(a){g.pV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.BR(a)||g.DR(a);this.events=new g.TJ(this);g.M(this,this.events);this.events.T(this.player,g.ZI("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.$I("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.lc);this.events.T(window,"focus",this.Bca);this.load();var b=g.yf("STYLE");(g.nf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Hf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},hqb=function(a){return a.player.getVideoData().Lf?"current":a.Z?"new":"current"},P3=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},iqb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=fqb(f,hqb(a))));Q3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Xv;d&&(c.postParams={ad_tracking:d});if(b=g.CXa(b))if(b=g.je(b),b=g.de(b))a.C=g.QA(b,c)},Q3=function(a,b,c){c=c===void 0?!0:c;
a.player.sf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&jqb(a);c=[];d=new g.YI(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.QT(a.player,a.B.element,4),a.D=new g.AF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=kqb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.QT(a.player,f.element,4);var h=new g.YI(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);lqb(a,f,e)}else g.wE(new g.SB("buildEndscreenElement null",
e))}a.player.kf(c);a.lc()}},jqb=function(a){var b=g.rE(),c=g.sE();
c&&b&&a.endscreen.visualElement&&g.wA(g.FE)(void 0,c,b,a.endscreen.visualElement)},kqb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.ND||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:R3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:S3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.aw(b.title||"")},va:b.title},{I:"div",S:b.rF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.ND||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:R3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:S3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.aw(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.ND||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.aw(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:R3(b)}]};c=new g.W(c);var d=g.of(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Tv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.ZV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.ND||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.aw(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:R3(b)},{I:"div",S:"ytp-ce-expanding-icon",W:mqb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.ND||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.aw(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:R3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Tv(c.element,"ytp-ce-placeholder");return c},R3=function(a){if(a.BX)var b=a.BX.thumbnails;
return mqb(b?b[b.length-1].url:null)},mqb=function(a){return a?{style:"background-image: url("+a+")"}:{}},lqb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Tv(b.element,"ytp-ce-force-expand"),T3(a,c.id,!0)):(g.Vv(b.element,"ytp-ce-force-expand"),g.Vv(b.element,"ytp-ce-element-hover"),T3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){nqb(a,b,c)});
b.listen("mouseleave",function(){oqb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Tv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){pqb(a,c,m)});
b.listen("keypress",function(m){pqb(a,c,m)});
b.listen("focus",function(){nqb(a,b,c)});
b.listen("blur",function(){oqb(a,b,c)});
b.listen("touchstart",function(){nqb(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Vv(b.element,"ytp-ce-element-hover");g.Vv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},pqb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.Sv(d,"ytp-ce-element");){g.Sv(d,"subscribe-label")&&qqb(a,b);
if(g.Sv(d,"ytp-ce-channel-subscribe"))return;d=g.If(d)}if(!d||g.Sv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])oqb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.qea==="new")qqb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(S3(a,b.targetUrl)),c=g.de(c),g.bG(c,void 0,b.sessionData);else{var e=g.MR(a.player.U())||a.player.getVideoData().Lf,f=function(){var h=S3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.BA(h);e&&n&&
(n.v||n.list)?a.player.ip(n.v,l,n.list,!1,void 0,m||void 0):g.jza(h,l)};
qqb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.TR(a)+b}else return"";return b},nqb=function(a,b,c){g.Sv(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Tv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Lv(function(){g.Tv(b.element,"ytp-ce-element-hover")},200)).start():g.Tv(b.element,"ytp-ce-element-hover"),U3(a,c.Q9),T3(a,c.id,!0))},oqb=function(a,b,c){g.Vv(b.element,"ytp-ce-element-hover");
g.Vv(b.element,"ytp-ce-force-expand");T3(a,c.id,!1)},T3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Xv(a.j[e].element,"ytp-ce-element-shadow-show",c)},U3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||P3(a))c&&c();else{b=rqb(a,b);var e=0,f=!1,h=new g.Lv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.lD(b[a],d)}},qqb=function(a,b,c){U3(a,b.clickUrls,c);
(a=g.sE())&&b.b$&&g.ME(a,b.visualElement)},rqb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(sqb(b[d],c));return a},sqb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},tqb=function(a){return typeof a==="string"?a:""},V3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},uqb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W3=function(a){return a.value?a.value:null},X3=function(a){if(!a)return null;
var b=g.je(tqb(a.value));b=g.de(b);if(!b)return null;var c=V3(a.target,vqb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new uqb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},wqb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},zqb=function(a){if(!a)return null;
var b=V3(a.type,xqb),c=V3(a.trigger,yqb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X3(a?a:null);return b?new wqb(b,c,a):null},Aqb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Bqb=function(a,b){return g.Db(a.action,b)},Cqb=function(a,b){this.context=a;
this.j=b},Dqb=function(a){return a.customMessage?Y3("div","iv-card-message",a.customMessage):""},Z3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},Eqb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},Y3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.aw(c);return{I:a,W:b,va:c}},Fqb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ZD&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ZD+");");c.dir=g.aw(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,W:c,V:d}},$3=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.lj.click,5)}},Gqb=function(a,b){this.merchant=a;
this.price=b},Hqb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Iqb=function(a,b){return b?b:Hqb(a)?"current":"new"},a4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.sb=!1;this.Xa=new Map;this.fb=new Map;this.context.J.addEventListener(g.ZI("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.$I("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},b4=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.TM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.sb=!1});
a.context.j.listen(b,"touchmove",function(){a.sb=!0})},Jqb=function(a){var b;
return((b=g.V(a,g.mF))==null?0:b.url)?g.V(a,g.mF).url:(a=g.V(a,g.LS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c4=function(a,b,c){return{aZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
f2:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
oM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Kqb=function(a,b,c){a4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ib=this.Na=this.Lb=this.C=this.isInitialized=!1;this.cards=[];this.Eb=this.Z=this.La=this.G=this.Wa=this.j=null;this.qa=[];this.ra=this.N=this.If=this.Ha=null;this.K=0;this.Fa=new g.Lv(function(){},c.X.Qk?4E3:3E3);
g.M(this,this.Fa);this.gb=new g.Lv(function(){});
g.M(this,this.gb);this.Ca=new Cqb(c,function(e,f,h,l,m,n){b4(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.M(this,this.Y);this.D=this.Y.element;this.eb=new g.AF(this.Y,330);g.M(this,this.eb);this.Kb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Lb&&d4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Lb=d.C)&&e4(d)});
this.Ta=new g.TJ(this);g.M(this,this.Ta);this.J.addEventListener("videodatachange",this.Ut.bind(this))},Lqb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e4(a)});
var c=b.headerText;g.Kf(a.Kb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ha=g.qE(b.trackingParams);a.N=g.qE(b.closeTrackingParams);a.If=g.qE(b.iconTrackingParams)},Mqb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ib("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$E(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,lj:{},Fp:null,Qj:e.trackingParams?g.qE(e.trackingParams):null,If:f&&f.trackingParams?g.qE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
ZD:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f4(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$E(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:g4(a,c,b,f),sponsored:!1,lj:c4(f,e,f.command),Fp:f.trackingParams?g.qE(f.trackingParams):null,Qj:e.trackingParams?g.qE(e.trackingParams):null,If:l&&l.trackingParams?g.qE(l.trackingParams):null,imageUrl:h4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.$E(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,ZD:null,title:f.title?g.$E(f.title):"",customMessage:f.callToAction?g.$E(f.callToAction):"",url:g.V(f.command,g.mF).url?X3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.mF).url}):null,onClickCommand:null};f4(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.$E(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,lj:c4(e,f,e.endpoint),Fp:e.trackingParams?g.qE(e.trackingParams):null,Qj:f.trackingParams?g.qE(f.trackingParams):null,If:l&&l.trackingParams?g.qE(l.trackingParams):null,channelId:g.V(e.endpoint,g.$S).browseId,customMessage:e.customText?g.$E(e.customText):null,profileImageUrl:h4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.$E(e.channelName):"",metaInfo:[e.subscriberCountText?g.$E(e.subscriberCountText):""],url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.$S).canonicalBaseUrl?g.V(e.endpoint,g.$S).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.$S).browseId}),onClickCommand:null};f4(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.$E(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,lj:c4(e,f,e.action),Fp:e.trackingParams?g.qE(e.trackingParams):null,Qj:f.trackingParams?g.qE(f.trackingParams):null,If:l&&l.trackingParams?g.qE(l.trackingParams):null,yH:h4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.$E(e.customMessage):null,playlistVideoCount:g.$E(e.playlistVideoCount),title:e.playlistTitle?g.$E(e.playlistTitle):"",metaInfo:[e.channelName?g.$E(e.channelName):
"",e.videoCountText?g.$E(e.videoCountText):""],url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Jqb(e.action)}),onClickCommand:null};f4(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.$E(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,lj:c4(e,f,e.action),Fp:e.trackingParams?g.qE(e.trackingParams):null,Qj:f.trackingParams?g.qE(f.trackingParams):null,If:l&&l.trackingParams?g.qE(l.trackingParams):null,yH:h4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.$E(e.lengthString):null,customMessage:e.customMessage?g.$E(e.customMessage):null,title:e.videoTitle?g.$E(e.videoTitle):"",metaInfo:[e.channelName?g.$E(e.channelName):
"",e.viewCountText?g.$E(e.viewCountText):""],isLiveNow:!!e.badge,url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Jqb(e.action)}),onClickCommand:null};f4(a,b)}}}}}a.K++},h4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},g4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Oqb=function(a,b){if(b=Nqb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Cf.id),g.Hf(b.mO),g.Hb(a.cards,b),a.AI(),i4(a)},d4=function(a,b,c){if(!a.C){a.eb.show();
a.Wa=new g.Lv(function(){g.Tv(a.context.J.getRootNode(),g.CY.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Ta.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.sE();d&&a.Ha&&a.N&&g.KE(d,[a.Ha,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.UZ||(f.UZ=!0,Pqb(a.context.logger,f.Cf.lj.aZ,b)),d&&g.KE(d,[f.Cf.Fp]);G3(a.J);c&&(a.G=new g.Lv(function(){a.La=a.Z;a.Eb.focus()},330),a.G.start())}},e4=function(a){a.C&&(a.eb.hide(),g.DB(a.Ta),g.Vv(a.context.J.getRootNode(),g.CY.IV_DRAWER_OPEN),a.C=!1,G3(a.J),a.G&&a.G.stop(),a.G=new g.Lv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Qqb=function(a){g.Uv(a.Jb(),
[g.CY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.QT(a.J,a.D,5);a.PD();a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.Eb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},Rqb=function(a){a.qa.push(g.zD("iv-teaser-shown",a.L4,a));
a.qa.push(g.zD("iv-teaser-hidden",a.u$,a));a.qa.push(g.zD("iv-teaser-clicked",a.K4,a));a.Ib=!0},Sqb=function(a,b){var c;
return b.onClickCommand&&((c=g.V(b.onClickCommand,g.vmb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},Tqb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.$Va(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.V(h[0],g.z3a))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},f4=function(a,b){if(!Sqb(a,b)||Tqb(a,b)){var c=Uqb(a,b);
if(c){var d={Cf:b,mO:c.element,UZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ib||Rqb(a),Oqb(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||Qqb(a);Oqb(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.AI()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,i4(a),Vqb(a,d),d4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Wqb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Wqb(a,d)}),i4(a))}}},Uqb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Fqb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?W3(b.url)||"":""},V:[Z3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[Y3("h2",void 0,b.title),d]}]}]};c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],W:{href:W3(b.url)||"","data-ytid":b.channelId},V:[Z3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Dqb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Eqb(b)]}]}]};c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:W3(b.url)||""},V:[Z3(b.yH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Dqb(b),Y3("h2","iv-card-primary-link",b.title),Eqb(b)]}]}]};
c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Fqb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?W3(b.url)||"":"";c={I:"div",Ka:c,W:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[Y3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Kf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Dd(d,"adInfo");$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:((c=b.url)==null?void 0:W3(c))||""},V:[Z3(b.yH,d),{I:"div",S:"iv-card-content",V:[Dqb(b),Y3("h2","iv-card-primary-link",b.title),Eqb(b),f]}]}]};c=new g.W(e);$3(a,g.sf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Xqb=function(a){if(a.j)return a.j.Cf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.bs(a.cards,function(c){return c.Cf.type==="productListing"})}return g.bs(a.cards,function(c){return c.Cf.type==="productListing"})},i4=function(a){g.Xv(a.J.getRootNode(),"ytp-cards-shopping-active",Xqb(a))},Wqb=function(a,b){if(!g.Sv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.sE(),d=a.j?a.j.Cf.If:a.If;
c&&d&&g.LE(c,[d]);a.j=b;i4(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Cf.teaserDurationMs&&a.J.bC(!0,{teaserText:b.Cf.teaserText,durationMs:b.Cf.teaserDurationMs,onClickCommand:b.Cf.onClickCommand});a.gb.isActive()||((!a.C||!a.Fa.isActive()&&a.Na)&&Vqb(a,b),a.gb.start(910+b.Cf.teaserDurationMs))}},Vqb=function(a,b){a.Y.Hb?(b=new L3([0,
a.B.scrollTop],[0,b.mO.offsetTop],600,cqb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.WE(a.Y,!0),a.B.scrollTop=b.mO.offsetTop,g.WE(a.Y,!1))},j4=function(a){return a.j&&a.j.Cf?a.j.Cf:a.cards[0]&&a.cards[0].Cf?a.cards[0].Cf:null},Nqb=function(a,b){return g.Db(a.cards,function(c){return c.Cf.id===b})},k4=function(a,b,c){a4.call(this,a,b);
this.annotation=c;this.isActive=!1},Yqb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l4=function(a,b,c){k4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Zqb=function(a,b){var c=c===void 0?0:c;
var d=Upb(b).width;g.Qs(b,d);c=new aqb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,bqb);g.M(a,c);a.context.C.listen(c,"begin",function(){g.Ws(b,!0)});
c.play()},brb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.ZV(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Ws(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Js(l,"right",b.image_width+"px");g.Bf(a.Jb(),l);a.C=new g.Lv(function(){$qb(a,h,l)},500);
g.M(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){arb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},arb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Vs(b);a.j||(b.style.width=g.Ps(f.width,!0),c.style.width=g.Ps(f.width,!0));g.Js(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Js(d,"right","1px");a.D=!0;g.Ws(b,!0);a.G=new g.Lv(function(){g.Tv(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},$qb=function(a,b,c){g.Vv(a.Jb(),"iv-branding-active");
a.K=new g.Lv(function(){g.Ws(b,!1);a.j||(c.style.width=g.Ps(0,!0))},250);
a.K.start();a.D=!1},crb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},drb=function(a,b,c){k4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.Lv(function(){d.j.setAttribute("aria-hidden","true");g.Ws(d.C,!1);g.Ws(d.B,!0)},700,this);
g.M(this,this.G)},grb=function(a,b,c){c.stopPropagation();
erb(a);frb(a,b);a.j.focus()},hrb=function(a){a.isCollapsed||a.Z||a.D||(g.Tv(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},erb=function(a){a.G.stop();
a.isCollapsed&&(g.Wv(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ws(a.B,!1),g.Ws(a.C,!0))},frb=function(a,b){a.D||(a.D=g.og(function(){irb(this);
hrb(this)},b,a))},irb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},jrb=function(a){this.J=a},Pqb=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.dv(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.lD(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},krb=function(a){g.pV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new jrb(this.player);this.D=new g.TJ(this);this.G=this.N=null;this.events=new g.TJ(this);this.dh=this.Y=this.j=null;this.ra=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.M4,this);this.subscribe("resize",this.eL,this);this.player.U().Na.subscribe("vast_info_card_add",this.f0,this);g.M(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.B);g.QT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.M(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.Xu()&&this.load();var c=this.createElement({I:"style"});(g.nf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Hf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},lrb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Ws(a,!1);return a},mrb=function(a,b){b=!b.isCued()&&!g.HF(b,1024);
g.WE(a.B,b);g.WE(a.C,b)},nrb=function(a,b,c){a.Z=!0;
a.G=g.QA(b,c)},orb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(orb(a,e))}return c},srb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.JA(h)&&h.responseXML?h.responseXML:null)&&prb(a,h)}};
g.$B()&&(d.onFinish=qrb(a,d.onFinish));d.postParams={ic_only:"1"};rrb(d,c);a.Z=!0;g.QA(b.Wa,d)}}},rrb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GI&&(a.postParams.ic_coll=b.GI);b.nO&&(a.postParams.ic_xml=b.nO);b.tM&&(a.postParams.ic_track=b.tM)},trb=function(a){var b=new g.W({I:"div"});
g.Ws(b.element,!1);var c=new Kqb(a.player,b.element,n4(a));g.M(c,b);b.Ja(a.B.element);c.jH();return c},vrb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,urb(a,b),b.headerText&&a.dh&&(c=g.$E(b.headerText),a.dh.setAttribute("title",c))},n4=function(a){if(!a.Y){var b=new dqb(a);
g.M(a,b);var c=new g.pq(a);g.M(a,c);a.Y=new crb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Aj)}return a.Y},prb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.sE();if(e){var f=g.rE();f&&g.wA(g.Ixa)(void 0,e,f,[g.qE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=orb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=V3(f.type,wrb),p=V3(f.style,xrb),q=tqb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=zqb;if(t==null)var u=null;else if(g.cb(t)){l=[];for(var w=g.v(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new Aqb(m,n,p,u,r):null}else e=null}catch(ma){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=lrb(f),L=null;switch(l.type){case "branding":if(f.player.U().Ed)break;f.B.element.appendChild(H);L=new l4(H,n4(f),l);break;case "promotion":g.QT(f.player,H,4),L=new drb(H,n4(f),l)}L&&L.jH();if(f=L)g.M(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=trb(a),g.M(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={aZ:f.impression,click:f.click,close:f.close,f2:f.teaser_impression,oM:f.teaser_click},l=e.tracking_params||{},L=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,lj:f,Fp:l.card?g.qE(l.card):null,Qj:l.teaser?g.qE(l.teaser):null,If:l.icon?g.qE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,lj:f,
Fp:l.card?g.qE(l.card):null,Qj:l.teaser?g.qE(l.teaser):null,If:l.icon?g.qE(l.icon):null,yH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "productListing":e.signin_url&&(L=X3({target:"current",value:e.signin_url}));N=[];for(var P=e.offers||[],fa=0;fa<P.length;fa++)N.push(new Gqb(g.bf(P[fa].merchant),
g.bf(P[fa].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,lj:f,Fp:l.card?g.qE(l.card):null,Qj:l.teaser?g.qE(l.teaser):null,If:l.icon?g.qE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,ZD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Jrb:L,Irb:e.signin_title?e.signin_title:void 0,Hrb:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};f4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,lj:f,Fp:l.card?g.qE(l.card):
null,Qj:l.teaser?g.qE(l.teaser):null,If:l.icon?g.qE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,ZD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,lj:f,Fp:l.card?g.qE(l.card):null,Qj:l.teaser?g.qE(l.teaser):null,If:l.icon?g.qE(l.icon):null,yH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},f4(H,c)}}else Lqb(a.j,e);c=!0}}c&&
(G3(a.player),a.eL())},urb=function(a,b){var c=!1;
a.j||(a.j=trb(a),g.M(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Mqb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.gT(f)||(c=a.j,d=b.headerText?g.$E(b.headerText):"",g.Kf(c.Kb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ha=b.trackingParams?g.qE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.qE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.If=b.icon.infoCardIconRenderer.trackingParams?g.qE(b.icon.infoCardIconRenderer.trackingParams):null,a.eL());G3(a.player)}},yrb=function(a,b,c,d,e){if(!a.player.U().Ed){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.$S)&&g.V(b.navigationEndpoint,g.$S).browseId&&f.push(new wqb("openUrl","click",new uqb("/channel/"+g.V(b.navigationEndpoint,g.$S).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.aT)){d.channel_id=g.V(b.subscribeButton,g.aT).channelId;var l;b=g.V(b.subscribeButton,g.aT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.$E(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.$E(b.subscriberCountText))):(b.subscriberCountText&&(e=g.$E(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.$E(b.subscriberCountWithSubscribeText)));var m,n=((m=g.V((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.z2))==null?void 0:m.url)||"";l={subscribeText:g.$E(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.$E(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Aqb(c,"branding","branding",f,d);l=lrb(a);a.B.element.appendChild(l);f=new l4(l,n4(a),f);f.jH();g.M(f,f);a.K[c]=f}},qrb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.Ma()||a.ra.push(g.Ev.Qi(function(){b.apply(null,g.qa(c))}))}},zrb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.JT.prototype.bC=g.ea(28,function(a,b){var c=g.HV(this.Ab());c&&c.bC(a,b)});
var I3={},J3=null;g.nb(L3,g.Yv);g.k=L3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;K3(this);this.startTime=a=g.lb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.WK();this.Kn("play");this.isPaused()&&this.Kn("resume");this.j=1;var b=g.fb(this);b in I3||(I3[b]=this);Xpb();Ypb(this,a);return!0};
g.k.stop=function(a){K3(this);this.j=0;a&&(this.progress=1);Zpb(this,this.progress);this.onStop();this.Zr()};
g.k.pause=function(){this.isPlaying()&&(K3(this),this.j=-1,this.Kn("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.Kn("destroy");L3.Rf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.SM=function(){this.Kn("animate")};
g.k.Kn=function(a){this.dispatchEvent(new $pb(a,this))};
g.nb($pb,g.Ab);g.nb(M3,L3);M3.prototype.C=function(){};
M3.prototype.SM=function(){this.C();M3.Rf.SM.call(this)};
M3.prototype.Zr=function(){this.C();M3.Rf.Zr.call(this)};
M3.prototype.WK=function(){this.C();M3.Rf.WK.call(this)};
g.nb(aqb,M3);aqb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(dqb,g.I);g.k=dqb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.xB(a,b,c);this.j.push(a);return a};
g.k.LF=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=Vpb(a,b,c);this.j.push(a);return a};
g.k.Qc=function(a){g.yB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.yB(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.I.prototype.xa.call(this)};g.y(gqb,g.pV);g.k=gqb.prototype;g.k.load=function(){g.pV.prototype.load.call(this);if(!P3(this)){var a=g.DXa(this.player.getVideoData());a?(a=fqb(a,hqb(this)),Q3(this,a,!1)):iqb(this)}};
g.k.unload=function(){Q3(this,null);this.C&&(this.C.abort(),this.C=null);g.pV.prototype.unload.call(this)};
g.k.Uh=function(a,b){return P3(this)?a==="loadCustomEndscreenRenderer"?(a=fqb(b,"new"),Q3(this,a),!0):null:null};
g.k.getOptions=function(){return P3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.lc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Arb.length;f++){var h=Math.abs(b.width-Arb[f]);if(e===-1||d>=h)e=f,d=h}d=Brb[e];this.B&&g.Js(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Us(e.element,m,f);g.Qs(e.element,n,p);g.Wv(e.element,Crb);m>256||f>256?g.Tv(e.element,"ytp-ce-large-round"):m>96||f>96?g.Tv(e.element,"ytp-ce-medium-round"):g.Tv(e.element,"ytp-ce-small-round");g.Wv(e.element,Drb);m=h.left+h.width/2;h=h.top+l/2;g.Tv(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Wv(e.element,Brb);g.Tv(e.element,d);(e=g.of(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Js(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")U3(this,this.endscreen.impressionUrls),(a=g.sE())&&this.endscreen.visualElement&&g.JE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Tv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Tv(b,"ytp-ce-shown");U3(this,c.impressionUrls);(b=g.sE())&&g.JE(b,c.visualElement);this.player.U().N&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Vv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Vv(b,"ytp-ce-shown");this.player.U().N&&this.player.jb("endscreenelementhidden",a)}};
g.k.Bca=function(a){var b=this;a.target===window&&(new g.Lv(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Wv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Arb=[346,426,470,506,570,640,853,1280,1920],Brb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Drb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Crb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var vqb={uwa:"current",KXa:"new"};var xqb={CLOSE:"close",B0a:"openUrl",SUBSCRIBE:"subscribe"},yqb={Fua:"click",CLOSE:"close",CIa:"hidden",K6a:"rollOut",L6a:"rollOver",C8a:"shown"};Aqb.prototype.Le=function(){var a=Bqb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var xrb={Toa:"anchored",F3:"branding",CHANNEL:"channel",kwa:"cta",FIa:"highlightText",JMa:"label",PLAYLIST:"playlist",POPUP:"popup",Mab:"speech",SUBSCRIBE:"subscribe",Ceb:"title",VIDEO:"video",gmb:"website"},wrb={F3:"branding",gsa:"card",sya:"drawer",EIa:"highlight",bTa:"marker",U4a:"promotion",TEXT:"text",Onb:"widget"};g.y(a4,g.I);g.k=a4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.YI(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.fb.set(a,e);this.context.J.kf([a])};
g.k.jH=function(){this.context.B.subscribe("resize",this.AI,this)};
g.k.Jb=function(){return this.element};
g.k.TM=function(a,b,c,d,e,f){if(this.sb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Hf(this.Jb())};
g.k.AI=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W3(a);if(f){var h=Iqb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Lf||!1,n=g.BA(f||"");m&&n&&(n.v||n.list)?e.context.J.ip(n.v,b,n.list,!1):g.bG(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);m4(this.context.logger,c,l,d);Hqb(f)||(c=g.sE(),d=b.itct,c&&d&&g.ME(c,g.qE(d)))}};
g.k.xa=function(){this.Xa.clear();this.fb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.y(Kqb,a4);g.k=Kqb.prototype;g.k.Ut=function(){this.ra&&f4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Vs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.AI=function(){var a=this.isAvailable();g.Ws(this.Jb(),a);g.Xv(this.context.J.getRootNode(),g.CY.IV_DRAWER_ENABLED,a);G3(this.J)};
g.k.destroy=function(){this.J.bC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.AD(this.qa);g.DB(this.Ta);this.Wa&&this.Wa.dispose();this.G&&this.G.dispose();a4.prototype.destroy.call(this)};
g.k.PD=function(){var a=this,b=g.tf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.D7,this);this.context.j.listen(this.B,"touchend",function(){a.Fa.start()});
this.context.j.listen(this.B,"scroll",this.a8,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Sv(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.zD("iv-button-shown",this.t$,this));this.qa.push(g.zD("iv-button-hidden",this.s$,this));Rqb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Eb(this.cards,function(c){return a.Cf.startMs>c.Cf.startMs||a.Cf.startMs===c.Cf.startMs&&a.Cf.timestamp>=c.Cf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.D7=function(){if(this.C){m4(this.context.logger,j4(this).lj.close);var a=g.sE();a&&this.N&&g.ME(a,this.N);e4(this)}};
g.k.a8=function(){g.Xv(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.t$=function(){var a=g.sE(),b=j4(this);b=b?b.If:this.If;a&&b&&g.KE(a,[b])};
g.k.s$=function(){var a=g.sE(),b=j4(this);b=b?b.If:this.If;a&&b&&g.LE(a,[b])};
g.k.L4=function(){var a=j4(this);m4(this.context.logger,a.lj.f2);var b=g.sE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Qj&&c.push(a.Qj);a.If&&c.push(a.If);c.length>0&&g.KE(b,c)}else g.KE(b,[a.Qj,a.If])};
g.k.u$=function(){var a=g.sE(),b=j4(this);a&&b&&g.LE(a,[b.Qj])};
g.k.K4=function(a){var b=j4(this),c=g.sE();this.j?a?(a=this.context.logger,m4(a,b.lj.oM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Qj&&g.ME(c,b.Qj)):(a=this.context.logger,m4(a,b.lj.oM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.If&&g.ME(c,b.If)):(a=this.context.logger,m4(a,b.lj.oM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.If&&g.ME(c,this.If))};g.y(k4,a4);k4.prototype.jH=function(){a4.prototype.jH.call(this);Yqb(this)};
k4.prototype.show=function(){a4.prototype.show.call(this);var a=g.sE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.KE(a,[g.qE(b.itct)])};
k4.prototype.hide=function(){a4.prototype.hide.call(this);var a=g.sE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.LE(a,[g.qE(b.itct)])};g.y(l4,k4);
l4.prototype.sy=function(){g.Tv(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ws(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.Le();c&&b4(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||brb(this,
a)};
l4.prototype.show=function(){if(!this.isActive&&(k4.prototype.show.call(this),this.N||(this.sy(),this.N=!0),g.Ws(this.Jb(),!0),this.isActive=!0,this.B)){try{Zqb(this,this.B)}catch(a){}g.Tv(this.context.J.getRootNode(),"ytp-branding-shown")}};
l4.prototype.hide=function(){this.isActive&&(k4.prototype.hide.call(this),g.Ws(this.Jb(),!1),this.isActive=!1,g.Vv(this.context.J.getRootNode(),"ytp-branding-shown"))};
l4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k4.prototype.destroy.call(this)};g.y(drb,k4);g.k=drb.prototype;
g.k.sy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promotion");this.Jb().tabIndex=0;var e=this.annotation.Le(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&b4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Me(f,W3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&b4(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.Tv(this.j,"iv-click-target");e&&b4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.Tv(this.j,"iv-click-target"),e&&b4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){grb(a,5E3,q)});
c.appendChild(this.B);g.Ws(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.s9,this);this.context.j.listen(this.Jb(),"mouseout",this.r9,this);this.context.j.listen(this.Jb(),"touchend",function(q){grb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.n9:this.m9,this);c.appendChild(this.C);g.Uv(this.Jb(),d);h&&(g.Bf(this.Jb(),h),n&&h.appendChild(n));g.Bf(this.Jb(),this.N);g.Bf(this.Jb(),c)};
g.k.show=function(){this.isActive||(k4.prototype.show.call(this),this.Y||(this.sy(),this.Y=!0),g.Ws(this.Jb(),!0),g.og(function(){g.Vv(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,irb(this),erb(this),frb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Tv(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.TM=function(a,b,c,d,e,f){return this.isCollapsed?!1:k4.prototype.TM.call(this,a,b,c,d,e,f)};
g.k.s9=function(a){this.Z=!0;grb(this,500,a)};
g.k.r9=function(){this.Z=!1;hrb(this)};
g.k.m9=function(a){a.stopPropagation();this.hide()};
g.k.n9=function(a){a.stopPropagation();irb(this);this.isCollapsed=!0;g.Tv(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();k4.prototype.destroy.call(this)};g.y(krb,g.pV);g.k=krb.prototype;g.k.Uh=function(a,b){if(!zrb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.e2(b))&&prb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Oqb(this.j,b),G3(this.player)),!0}return null};
g.k.getOptions=function(){return zrb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Xu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.rT(b)||g.CT(this.player.app)?!1:c===1&&!b.WY||a.Na.get(b.videoId)||g.hT(b)||g.EXa(b)?!0:!1};
g.k.eL=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Us(this.C.element,a.width,a.height);g.Qs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Un();a=this.j;b=b.width;g.Xv(a.D,"iv-drawer-small",b<=426);g.Xv(a.D,"iv-drawer-big",b>=1280)}};
g.k.M4=function(a){mrb(this,a.state);g.HF(a.state,2)&&(this.Wk()&&this.Cp()&&this.player.getPresentingPlayerType()!==2&&this.cC(!1),this.bC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.JA(h)&&h.responseXML?h.responseXML:null)&&(prb(b,h),g.Tv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.pV.prototype.load.call(this);mrb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.$B()&&(a=qrb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&rrb(e,f);f=f&&(f.nO||f.GI);if(!c.Gv||f)c.Wa?nrb(this,c.Wa,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.gT(h))&&!b.qa&&vrb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.QT(this.player,this.C.element,4);this.eL();(f=g.hT(c))&&urb(this,f);(f=g.EXa(c))&&f.featuredChannel&&yrb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.dh=g.tf("ytp-cards-button",this.player.getRootNode());g.gT(c)&&vrb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&nrb(this,b.Wa,a)};
g.k.unload=function(){this.player.sf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,G3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.pV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.f0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?srb(this):this.load())};
g.k.Wk=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Cp=function(){return!!this.j&&this.j.C};
g.k.cC=function(a,b,c){b=b===void 0?!1:b;this.Wk();this.j&&(a?c?d4(this.j,c,b):d4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e4(this.j))};
g.k.bC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.f0,this);g.Vv(this.player.getRootNode(),g.CY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Ev,c=0,d=a.length;c<d;c++)b.Wj(a[c]);this.ra.length=0;g.pV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.oV("annotations_module",krb);g.oV("creatorendscreen",gqb);})(_yt_player);
