(function(g){var window=this;'use strict';var Tvb=function(a,b){a.jb("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.Xv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.ih(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.lS&&(b.lengthText?(e=b.lengthText||null,f=b.sx||null):b.lengthSeconds&&(e=g.RF(b.lengthSeconds),f=g.RF(b.lengthSeconds,!0)));var h=!!d;d=h&&g.WVa(d).type==="RD";var l=b instanceof g.lS?b.isLivePlayback:null,m=b instanceof g.lS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.eJ("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.jl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.gt};b instanceof g.kS&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.U(),c=b.D;
g.W.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},l6=function(a,b){b=b===void 0?!1:b;
g.W.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.W({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.M(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.M(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ga("ytp-autonav-endscreen-link-container"),"click",this.KU);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ga("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({I:"div",S:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.W({I:"div",S:"ytp-autonav-endscreen-button-container"});g.M(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.W({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.T4,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.W({I:"a",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.M(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.KU,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Uvb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Lv(function(){Vvb(c)},
500);
g.M(this,this.D);this.JU();this.T(a,"autonavvisibility",this.JU);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.S4),this.T(a,"onAutonavCoundownStarted",this.jaa))},m6=function(a){var b=a.J.Un(!0,a.J.isFullscreen());
g.Xv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Rg(b));g.Xv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.jM);g.Xv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Jf());g.Xv(a.J.getRootNode(),"countdown-running",a.vl());g.Xv(a.container.element,"ytp-player-content",a.J.Jf());g.Js(a.overlay.element,{width:b.width+"px"});if(!a.vl()){a.J.Jf()?Wvb(a,Math.round(Xvb(a)/1E3)):Wvb(a);b=!!a.suggestion&&!!a.suggestion.gt;var c=a.J.Jf()||!b;
g.Xv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Xv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.WE(a.B,a.J.Jf());g.Xv(a.element,"ytp-enable-w2w-color-transitions",Yvb(a))}},Vvb=function(a){var b=Xvb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Wvb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.vl()?a.select(!0):a.vl()&&a.D.start()},Xvb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.YC;return a===-1||a===void 0?8E3:a}return a.J.Lt()>=0?a.J.Lt():g.sI(a.J.U().experiments,"autoplay_time")||1E4},Uvb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.ffa;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Yvb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},Wvb=function(a,b){b=b===void 0?-1:b;
a=a.j.Ga("ytp-autonav-endscreen-upnext-header");g.Cf(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.Af("Up next in $SECONDS".slice(0,d)));var e=g.yf("span");g.Rv(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Kf(e,b);a.appendChild(e);a.appendChild(g.Af("Up next in $SECONDS".slice(d+c.length)));return}}g.Kf(a,"Up next")},n6=function(a,b){g.W.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.W.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ga("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Lv(this.LI,5E3,this);this.B=0;var b=this.Ga("ytp-upnext-cancel");this.cancelButton=new g.W({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.listen("click",this.U4,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.M(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ga("ytp-upnext-autoplay-icon");this.T(b,"click",this.V4);this.api.createClientVe(b,this,115130);this.LU();this.T(a,"autonavvisibility",this.LU);this.T(a,"mdxnowautoplaying",this.Waa);this.T(a,"mdxautoplaycanceled",this.Xaa);g.Xv(this.element,"ytp-upnext-mobile",this.api.U().B)},Zvb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.YC;return a===-1||a===void 0?8E3:a}return a.api.Lt()>=0?a.api.Lt():g.sI(a.api.U().experiments,"autoplay_time")||1E4},$vb=function(a,b){b=Zvb(a,b);
var c=Math,d=c.min;var e=(0,g.rC)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.vl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.vl()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.W({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l6(this.player);g.M(this,this.B);this.B.Ja(this.element);a.getVideoData().Vf?this.j=this.B:(this.j=new o6(a),g.QT(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.W({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.M(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.TJ(this);g.M(this,this.D);g.M(this,this.table);this.table.Ja(this.element);this.table.show();g.M(this,this.N);this.N.Ja(this.table.element);this.hide()},q6=function(a){var b=a.Jf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r6=function(a,b){g.W.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.G1();this.buttonType===2&&g.Tv(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.G1);g.WE(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Re=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r6(a,2);g.M(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},awb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.ZV("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ml,b.subscribed,"trailer-endscreen",null,a,!1);g.M(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ga("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ua);this.Ua();this.hide()},t6=function(a){var b=a.U(),c=g.RJ||g.vR?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",Ka:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.TJ(this);g.M(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.TJ(this);g.M(this,this.B);this.K=new g.Lv(function(){g.Tv(b.element,"ytp-show-tiles")},0);
g.M(this,this.K);var c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},V:[g.bF()]});g.M(this,c);c.Ja(this.element);c.listen("click",this.Z4,this);this.table=new g.TE({I:"div",S:"ytp-endscreen-content"});g.M(this,this.table);this.table.Ja(this.element);c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},V:[g.cF()]});g.M(this,c);c.Ja(this.element);c.listen("click",this.Y4,this);a.getVideoData().Vf?this.j=new l6(a,!0):this.j=
new o6(a);g.M(this,this.j);g.QT(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v6=function(a){return g.RT(a.player)&&a.VD()&&!a.D},w6=function(a){var b=a.Jf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.M(this,this.watchButton);this.watchButton.Ja(this.element);g.Yjb(a)&&(this.j=new g.g2(a),g.M(this,this.j),this.B=new g.W({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.M(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},ewb=function(a){g.pV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.TJ(this);g.M(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.oB(g.ER(c))&&d&&!g.NT(a)?(this.B=!0,this.endScreen=new s6(a,g.ET(a))):a.fd()?this.endScreen=new x6(a):bwb(a)?(this.D=!0,cwb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.Kg?this.endScreen=new awb(a):this.endScreen=new n6(a);g.M(this,this.endScreen);g.QT(a,this.endScreen.element,4);dwb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.ZI("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.$I("endscreen"),function(e){b.onCueRangeExit(e)})},cwb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Ul&&a.C===b.Vf)return!1;a.j=b.Ul;a.C=b.Vf;return!0},bwb=function(a){a=a.U();
return a.Cd&&!a.Kg},dwb=function(a){a.player.sf("endscreen");
var b=a.player.getVideoData();b=new g.YI(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.YI(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.kf([b,c])};
g.JT.prototype.Lt=g.ea(15,function(){return this.app.Lt()});
g.G0.prototype.Lt=g.ea(14,function(){return this.getVideoData().xX});
g.FT.prototype.Cs=g.ea(13,function(a){this.Ei().Cs(a)});
g.nW.prototype.Cs=g.ea(12,function(a){this.j!==a&&(this.j=a,this.Ua())});
g.uX.prototype.Cs=g.ea(11,function(a){this.overflowButton&&this.overflowButton.Cs(a)});
g.FT.prototype.Ds=g.ea(10,function(a){this.Ei().Ds(a)});
g.sW.prototype.Ds=g.ea(9,function(a){this.j!==a&&(this.j=a,this.Ua())});
g.uX.prototype.Ds=g.ea(8,function(a){this.shareButton&&this.shareButton.Ds(a)});
g.FT.prototype.fC=g.ea(7,function(a){this.Ei().fC(a)});
g.SV.prototype.fC=g.ea(6,function(a){this.eS!==a&&(this.eS=a,this.Pq())});
g.FT.prototype.eC=g.ea(5,function(a){this.Ei().eC(a)});
g.uX.prototype.eC=g.ea(4,function(a){this.dS!==a&&(this.dS=a,this.Oq())});g.y(k6,g.W);k6.prototype.select=function(){this.J.ip(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tE||void 0)&&this.J.logClick(this.element)};
k6.prototype.onClick=function(a){g.hU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.y(l6,g.W);g.k=l6.prototype;g.k.TH=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.jl()),m6(this))};
g.k.vl=function(){return this.C>0};
g.k.oC=function(){this.vl()||(this.C=Date.now(),Vvb(this),Tvb(this.J,Xvb(this)),g.Xv(this.J.getRootNode(),"countdown-running",this.vl()))};
g.k.Xx=function(){this.Iq();Vvb(this);var a=this.j.Ga("ytp-autonav-endscreen-upnext-header");a&&g.Kf(a,"Up next")};
g.k.Iq=function(){this.vl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Iq()};
g.k.KU=function(a){g.hU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ga("ytp-autonav-endscreen-link-container")&&(a=this.j.Ga("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.jb("innertubeCommand",this.G),this.Iq()):this.select())};
g.k.T4=function(){this.J.logClick(this.cancelButton.element);g.LT(this.J,!0);this.cancelCommand&&this.J.jb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Uvb(this,b);var c;this.cancelCommand=(c=b.cfa)==null?void 0:c.command};
g.k.jaa=function(a){if(Yvb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.ZF(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.ZF(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.ZF(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.ZF(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.ZF(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.ZF(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Xv(this.element,"ytp-w2w-animate",!0)}};
g.k.S4=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.Xv(this.element,"ytp-w2w-animate",!1)};
g.k.JU=function(){var a=this.J.Jf();this.K&&this.Hb!==a&&g.WE(this,a);m6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ga("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Rg=function(a){return a.width<400||a.height<459};g.y(n6,g.W);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.VD=function(){return!1};
g.k.Jf=function(){return!1};
g.k.uZ=function(){return!1};g.y(o6,g.W);g.k=o6.prototype;g.k.LI=function(){this.notification&&(this.D.stop(),this.Qc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.TH=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.LU=function(){g.WE(this,this.api.Jf());this.api.logVisibility(this.element,this.api.Jf());this.api.logVisibility(this.Ga("ytp-upnext-autoplay-icon"),this.api.Jf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Jf())};
g.k.fba=function(){window.focus();this.LI()};
g.k.oC=function(a){var b=this;this.vl()||(g.BD("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.rC)(),this.j=new g.Lv(function(){$vb(b,a)},25),$vb(this,a),Tvb(this.api,Zvb(this,a)));
g.Vv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.vl=function(){return!!this.j};
g.k.Xx=function(){this.Iq();this.B=(0,g.rC)();$vb(this);g.Tv(this.element,"ytp-upnext-autoplay-paused")};
g.k.Iq=function(){this.vl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.LI(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.ih()}),this.C=this.T(this.notification,"click",this.fba),this.D.start())}this.Iq();this.api.nextVideo(!1,a)};
g.k.V4=function(a){!g.Jf(this.cancelButton.element,a.target)&&g.hU(a,this.api)&&(this.api.Jf()&&this.api.logClick(this.Ga("ytp-upnext-autoplay-icon")),this.select())};
g.k.U4=function(){this.api.Jf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.LT(this.api,!0)};
g.k.Waa=function(a){this.api.getPresentingPlayerType();this.show();this.oC(a)};
g.k.Xaa=function(){this.api.getPresentingPlayerType();this.Iq();this.hide()};
g.k.xa=function(){this.Iq();this.LI();g.W.prototype.xa.call(this)};g.y(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.D.T(this.player,"appresize",this.fD);this.D.T(this.player,"onVideoAreaChange",this.fD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.MU);this.D.T(this.player,"onAutonavCancelled",this.W4);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.LT(this.player,!1);g.RT(this.player)&&this.VD()&&!this.C?(q6(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.oC():this.videoData.autonavState===3&&this.j.Xx()):(g.LT(this.player,!0),q6(this));this.fD()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.Xx();q6(this)};
g.k.fD=function(){var a=this.player.Un(!0,this.player.isFullscreen());q6(this);m6(this.B);g.Xv(this.element,"ytp-autonav-cancelled-small-mode",this.Rg(a));g.Xv(this.element,"ytp-autonav-cancelled-tiny-mode",this.lK(a));g.Xv(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.Js(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Xv(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.MS(this.videoData);b&&(this.j.TH(b),this.j!==this.B&&this.B.TH(b))}if(a&&a.length)for(b=0;b<fwb.length;++b){var c=fwb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.M(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.fD()}};
g.k.MU=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Iq(),this.Hb&&this.fD()):(this.K=!0,this.Jf()&&(a===2?this.j.oC():a===3&&this.j.Xx()))};
g.k.W4=function(a){a?this.MU(1):(this.C=null,this.K=!1)};
g.k.VD=function(){return this.videoData.autonavState!==1};
g.k.Rg=function(a){return(a.width<910||a.height<459)&&!this.lK(a)&&!(a.width<=400||a.height<=360)};
g.k.lK=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Jf=function(){return this.Hb&&g.RT(this.player)&&this.VD()&&!this.C};
var fwb=[1,3,2,4];g.y(r6,g.W);g.k=r6.prototype;g.k.G1=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.iU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.wR(b)){var c={};g.wR(b)&&g.yT(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.SO(c,b);a=g.uo(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Hb&&this.Z)};
g.k.show=function(){g.W.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.logVisibility()};
g.k.Mc=function(a){g.W.prototype.Mc.call(this,a);this.logVisibility()};g.y(s6,n6);s6.prototype.show=function(){this.player.getPlayerState()!==3&&(n6.prototype.show.call(this),this.Re.eC(!0),this.Re.Ds(!0),this.J.U().He||this.Re.Cs(!0),this.J.logVisibility(this.element,!0),this.watchButton.Mc(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.Re.eC(!1);this.Re.Ds(!1);this.Re.Cs(!1);this.J.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.y(awb,n6);awb.prototype.Ua=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Ml;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.y(t6,g.W);t6.prototype.select=function(){this.api.ip(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tE||void 0)&&this.api.logClick(this.element)};
t6.prototype.onClick=function(a){if(g.wR(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.jl(),c={};g.wYa(this.api,c,"emb_rel_end");b=g.uo(b,c);g.iU(b,this.api,a)}else g.hU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Lf?!1:b.D};g.y(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Vq();this.B.T(this.player,"appresize",this.Vq);this.B.T(this.player,"onVideoAreaChange",this.Vq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.WM);this.B.T(this.player,"onAutonavCancelled",this.X4);a=this.videoData.autonavState;a!==this.Y&&this.WM(a);this.B.T(this.element,"transitionend",this.uca)};
g.k.destroy=function(){g.DB(this.B);g.wb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.Vv(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.VD=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Hb;n6.prototype.show.call(this);g.Vv(this.element,"ytp-show-tiles");this.player.U().B?g.Nv(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.LT(this.player,!1);v6(this)?(w6(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.oC():this.videoData.autonavState===3&&this.j.Xx()):(g.LT(this.player,!0),w6(this));a!==this.Hb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Hb;n6.prototype.hide.call(this);this.j.Xx();w6(this);a!==this.Hb&&this.player.logVisibility(this.element,!1)};
g.k.uca=function(a){a.target===this.element&&this.Vq()};
g.k.Vq=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.MS(d)];if(e.length){g.Tv(this.element,"ytp-endscreen-paginate");var f=this.J.Un(!0,this.J.isFullscreen());if(a=g.ET(this.J))a=a.Ih()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Us(f,n,p);g.Js(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.TH(g.MS(this.videoData));this.j instanceof
l6&&m6(this.j);g.Xv(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Ae(q+this.C,c),t!==0){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var w=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-u-4,C=Math.floor(n*(l+t)/a)-w-4;g.Qs(r.element,w,u);g.Us(r.element,C,A);g.Js(r.element,"transitionDelay",
(m+l)/20+"s");g.Xv(r.element,"ytp-videowall-still-mini",t===1);g.Xv(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,A);g.Xv(r.element,"ytp-videowall-still-round-large",t>=256);g.Xv(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.Xv(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.Sv(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,u),g.wR(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.jl(),u={},g.yT(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.uo(t,g.SO(u,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.Xv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Hf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.MS(a)?(this.C=0,this.videoData=a,this.Vq()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.Y4=function(){this.C+=this.stills.length;this.Vq()};
g.k.Z4=function(){this.C-=this.stills.length;this.Vq()};
g.k.uZ=function(){return this.j.vl()};
g.k.WM=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Iq(),this.Hb&&this.Vq()):(this.G=!0,this.Hb&&v6(this)&&(a===2?this.j.oC():a===3&&this.j.Xx()))};
g.k.X4=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.WM(1)}else this.D=null,this.G=!1;this.Vq()};
g.k.Jf=function(){return this.Hb&&v6(this)};g.y(x6,n6);x6.prototype.show=function(){if(this.player.getPlayerState()!==3){n6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.Xv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.ET(this.player))==null||c.fC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Mc(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;(a=g.ET(this.player))==null||a.fC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.y(ewb,g.pV);g.k=ewb.prototype;g.k.Xu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.fd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.MS(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!bwb(this.player)||d;a=a.Ij;c=this.player.FE();return d&&!a&&!c&&!b};
g.k.Jf=function(){return this.endScreen.Jf()};
g.k.Y9=function(){return this.Jf()?this.endScreen.uZ():!1};
g.k.xa=function(){this.player.sf("endscreen");g.pV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Ab().Ge.get("heartbeat"),d=g.MS(a);!d||b.videoId!==d.videoId||a.WV?(this.player.ip(b.videoId,void 0,void 0,!0,!0,b),c&&c.vK("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.pV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.pV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Xu()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){dwb(this);this.D&&cwb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.M(this,this.endScreen),g.QT(this.player,this.endScreen.element,4))};g.oV("endscreen",ewb);})(_yt_player);
