(function(g){var window=this;'use strict';var cxb=function(a,b){g.W.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],W:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",W:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",W:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",W:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",W:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.IT(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.GT(b.Ve(),this.element))},dxb=function(a){g.W.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.ph);this.T(a,"onStateChange",this.eea)},exb=function(a){g.pV.call(this,a);
this.B=new g.TJ(this);this.j=new dxb(this.player);this.j.hide();g.QT(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Xv(a.getRootNode(),"ytp-player-minimized",!0))};
g.y(cxb,g.W);cxb.prototype.onClick=function(){this.J.jb("onExpandMiniplayer")};g.y(dxb,g.W);g.k=dxb.prototype;
g.k.show=function(){this.j=new g.Kv(this.e5,null,this);this.j.start();if(!this.G){this.tooltip=new g.tX(this.player,this);g.M(this,this.tooltip);g.QT(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.me=new g.VV(this.player);g.M(this,this.me);this.B=new g.W({I:"div",S:"ytp-miniplayer-scrim"});g.M(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.V_);var a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Close"},V:[g.dF()]});g.M(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.OU);a=new cxb(this.player,this);g.M(this,a);a.Ja(this.B.element);this.C=new g.W({I:"div",S:"ytp-miniplayer-controls"});g.M(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.V_);var b=new g.W({I:"div",S:"ytp-miniplayer-button-container"});g.M(this,b);b.Ja(this.C.element);a=new g.W({I:"div",S:"ytp-miniplayer-play-button-container"});g.M(this,a);a.Ja(this.C.element);var c=new g.W({I:"div",S:"ytp-miniplayer-button-container"});
g.M(this,c);c.Ja(this.C.element);this.N=new g.FW(this.player,this,!1);g.M(this,this.N);this.N.Ja(b.element);b=new g.EW(this.player,this);g.M(this,b);b.Ja(a.element);this.nextButton=new g.FW(this.player,this,!0);g.M(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.mX(this.player,this);g.M(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.KW(this.player,this);g.M(this,this.progressBar);g.QT(this.player,this.progressBar.element,4);this.D=new g.W({I:"div",S:"ytp-miniplayer-buttons"});
g.M(this,this.D);g.QT(this.player,this.D.element,4);a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Close"},V:[g.dF()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.OU);a=new g.W({I:"button",Ka:["ytp-miniplayer-replay-button","ytp-button"],W:{"aria-label":"Close"},V:[g.pya()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.Jba);this.T(this.player,"presentingplayerstatechange",this.f5);this.T(this.player,"appresize",this.lc);
this.T(this.player,"fullscreentoggled",this.lc);this.lc();this.G=!0}this.player.getPlayerState()!==0&&g.W.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.xa.call(this)};
g.k.OU=function(){this.player.stopVideo();this.player.jb("onCloseMiniplayer")};
g.k.Jba=function(){this.player.playVideo()};
g.k.V_=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.ph=function(){g.Xv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.Eg=function(){this.progressBar.Sc();this.K.Sc()};
g.k.e5=function(){this.Eg();this.j&&this.j.start()};
g.k.f5=function(a){g.HF(a.state,32)&&this.tooltip.hide()};
g.k.lc=function(){g.T3a(this.progressBar,0,this.player.qb().getPlayerSize().width,!1);g.LW(this.progressBar)};
g.k.eea=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Ve=function(){return this.tooltip};
g.k.Zx=function(a,b,c,d,e){var f=0,h=d=0,l=g.Vs(a);if(b){c=g.Sv(b,"ytp-prev-button")||g.Sv(b,"ytp-next-button");var m=g.Sv(b,"ytp-play-button"),n=g.Sv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Ts(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Sv(b,"ytp-miniplayer-button-top-left"),f=g.Ts(b,this.element),b=g.Vs(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.qb().getPlayerSize().width;e=f+(e||0);l=g.ze(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.y(exb,g.pV);g.k=exb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Xv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.pV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.cn=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.oV("miniplayer",exb);})(_yt_player);
